export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const DELETE_FROM_FAVORITE = 'DELETE_FROM_FAVORITE';

export const DATA_REQUESTED = 'DATA_REQUESTED';
export const DATA_RECEIVED = 'DATA_RECEIVED';
export const DATA_NOT_RECEIVED = 'DATA_NOT_RECEIVED';
export const DATA_RESET = 'DATA_RESET';
